"""
This is a setup.py script generated by py2applet

Usage:

within conda enviroment: use brew-installed pyside (v1.2.2), because PySide is not supported by conda anymore

"""
import sys
sys.setrecursionlimit(2000)
from setuptools import setup

APP = ['Facepager.py']
OPTIONS = {'argv_emulation': False,

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
