"""
This is a setup.py script generated by py2applet

Usage:
    python osxsetup.py py2app

within conda enviroment: use brew-installed pyside (v1.2.2), because PySide is not supported by conda anymore

"""
import sys
#import macholib_patch
sys.setrecursionlimit(2000)
from setuptools import setup

APP = ['Facepager.py']
DATA_FILES = [('',['docs']),('',['ssl'])]
OPTIONS = {'argv_emulation': False,
'iconfile':'icon.icns',
 'includes': 'PySide,sqlite3,atexit,PySide.QtNetwork,PySide.QtWebKit,credentials,requests',
 'packages': 'sqlalchemy,dateutil'}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
